"use client";

import { useEffect, useRef, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowRight, ArrowUpRight, CodeXml, Workflow, Blocks, LifeBuoy, ScanLine, Layers3, UserRound, Check, CheckCheck, FileText, CircleCheck, Menu, Mail, Phone, ShieldCheck, Unplug, Network, Database, Monitor, Smartphone, Settings2, Search, PencilRuler, Rocket, HeartHandshake, Eye, Gem, LoaderCircle, X } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Sheet, SheetTrigger, SheetContent, SheetHeader, SheetTitle, SheetDescription, SheetClose } from "@/components/ui/sheet";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { contactSchema, type ContactValues } from "@/lib/contact";
import Hero3D from "@/components/hero-3d";

const CONTACT = { email: "servicios@msexpressrd.com", phone: "(809) 221-3936", tel: "+18092213936", whatsapp: "https://wa.me/18092213936", privacy: "https://msexpressrd.com/politica-privacidad", terms: "https://msexpressrd.com/t%C3%A9rminos-y-condiciones" };
const nav = [{ label: "Soluciones", id: "soluciones" }, { label: "Cómo trabajamos", id: "proceso" }, { label: "Proyectos", id: "proyectos" }, { label: "Nosotros", id: "nosotros" }, { label: "Preguntas", id: "preguntas" }];

function Brand() {
  return <a href="#inicio" className="brand" aria-label="MS Express — Multi Servicios Express, inicio"><img src="/logo_msexpress.png" alt="" className="brand-logo" width={70} height={64} /></a>;
}

function Navbar() {
  const [scrolled, setScrolled] = useState(false);
  const [open, setOpen] = useState(false);
  useEffect(() => { const update = () => setScrolled(window.scrollY > 20); update(); window.addEventListener("scroll", update, { passive: true }); return () => window.removeEventListener("scroll", update); }, []);
  return <header className={"nav-shell " + (scrolled ? "scrolled" : "")}><div className="wrap nav-inner"><Brand /><nav className="desktop-nav" aria-label="Navegación principal">{nav.map(item => <a key={item.id} href={"#" + item.id}>{item.label}</a>)}</nav><a href="#contacto" className="btn btn-primary nav-cta">Hablemos <ArrowUpRight aria-hidden="true" /></a><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><button className="mobile-menu-button" aria-label="Abrir menú"><Menu size={21} /></button></SheetTrigger><SheetContent className="mobile-sheet" showCloseButton={false}><SheetClose asChild><button className="absolute top-5 right-5 p-2" aria-label="Cerrar menú"><X size={21} /></button></SheetClose><SheetHeader className="p-0"><SheetTitle className="text-2xl">MS Express</SheetTitle><SheetDescription>Software que mueve tu empresa.</SheetDescription></SheetHeader><nav className="mobile-links" aria-label="Menú móvil">{nav.map(item => <a key={item.id} href={"#" + item.id} onClick={() => setOpen(false)}>{item.label}</a>)}</nav><a href="#contacto" className="btn btn-primary" onClick={() => setOpen(false)}>Cuéntanos tu proyecto <ArrowRight /></a><a className="mobile-contact" href={"mailto:" + CONTACT.email}>{CONTACT.email}</a></SheetContent></Sheet></div></header>;
}

function Hero() {
  return <><Hero3D /><ValueBand /></>;
}
function ValueBand() {
  const items = [{ icon: CodeXml, title: "Software a la medida", text: "Tu forma de trabajar, como punto de partida." }, { icon: Workflow, title: "Automatización de procesos", text: "Menos pasos manuales en tu día a día." }, { icon: Blocks, title: "Una operación conectada", text: "Integraciones según lo que necesitas." }, { icon: LifeBuoy, title: "Acompañamiento cercano", text: "De la idea al uso diario de tu solución." }];
  return <div className="value-band"><div className="wrap value-grid">{items.map(item => <div className="value-item" key={item.title}><div className="value-top"><item.icon aria-hidden="true" /><h3>{item.title}</h3></div><p>{item.text}</p></div>)}</div></div>;
}

type Solution = { id: string; title: string; teaser: string; icon: LucideIcon; label: string; problem: string; description: string; tags: string[]; result: string; flow: string[]; flowIcons: LucideIcon[] };
const solutions: Solution[] = [
  { id: "desarrollo", title: "Desarrollo a la medida", teaser: "Software que se ajusta a tu empresa.", icon: CodeXml, label: "DESARROLLO Y MANTENIMIENTO", problem: "Tu operación no cabe en una plantilla.", description: "Construimos y mantenemos sistemas alrededor de tus procesos. Automatizamos tareas manuales para que las herramientas se adapten a tu empresa, y no al revés.", tags: ["Sistemas a la medida", "Automatización", "Mantenimiento"], result: "Objetivo: una operación más eficiente y menos trabajo manual.", flow: ["Tu proceso", "Tu sistema", "Tu equipo"], flowIcons: [Workflow, CodeXml, UserRound] },
  { id: "consultoria", title: "Consultoría informática", teaser: "Claridad antes de construir.", icon: ScanLine, label: "CONSULTORÍA INFORMÁTICA", problem: "Sabes que algo puede funcionar mejor.", description: "Evaluamos tus procesos para identificar tareas innecesarias, problemas y oportunidades técnicas. A partir de ese diagnóstico, planteamos soluciones viables.", tags: ["Evaluación de procesos", "Diagnóstico", "Soluciones técnicas"], result: "Objetivo: decidir qué mejorar con una dirección clara.", flow: ["Analizar", "Priorizar", "Resolver"], flowIcons: [Search, Layers3, CircleCheck] },
  { id: "sistemas", title: "Sistemas para tu negocio", teaser: "Herramientas para el trabajo de cada día.", icon: Layers3, label: "SUMINISTRO DE SOFTWARE", problem: "Necesitas organizar tu gestión diaria.", description: "Contamos con programas informáticos para apoyar las actividades de empresas y profesionales. Exploremos qué sistema encaja con tu necesidad y su alcance.", tags: ["Financiero FAB", "Facturación e inventario", "Alquileres FAB", "Dulus"], result: "Objetivo: apoyar la gestión con herramientas útiles.", flow: ["Necesidad", "Software", "Gestión"], flowIcons: [FileText, Monitor, Database] },
];
function MiniDemo({ solution }: { solution: Solution }) {
  return <div className="mini-demo" aria-label="Diagrama ilustrativo de la solución"><div className="mini-flow">{solution.flow.map((label, i) => { const Icon = solution.flowIcons[i]; return <div key={label} className="contents">{i > 0 && <span className="mini-connector" aria-hidden="true" />}<div className="mini-block"><Icon aria-hidden="true" />{label}</div></div>; })}</div><div className="mini-code"><span>Diseñado alrededor de tu operación</span><span aria-hidden="true">↗</span></div></div>;
}
function SolutionPanel({ solution }: { solution: Solution }) {
  return <div className="solution-panel"><div className="panel-top"><span>{solution.label}</span><solution.icon aria-hidden="true" /></div><MiniDemo solution={solution} /><span className="problem-label">EL PUNTO DE PARTIDA</span><h3>{solution.problem}</h3><p>{solution.description}</p><div className="tags">{solution.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="expected"><CircleCheck aria-hidden="true" /><span>{solution.result}</span></div><a href="#contacto" className="text-link" onClick={() => window.dispatchEvent(new CustomEvent("solution-interest", { detail: solution.title }))}>Conocer solución <ArrowRight aria-hidden="true" /></a></div>;
}
function Solutions() {
  return <section className="section" id="soluciones"><div className="wrap"><div className="section-topline reveal"><div><p className="eyebrow"><span className="chapter-number">01</span>SOLUCIONES</p><h2 className="section-heading">Tecnología que se adapta a cómo trabaja tu empresa.</h2><p className="section-intro">Partimos de tu operación actual y construimos la solución que realmente necesitas.</p></div><p className="side-note">No empezamos por la tecnología.<br />Empezamos por lo que necesitas resolver.</p></div><Tabs defaultValue="desarrollo" orientation="vertical" className="solution-tabs desktop-solutions reveal"><TabsList className="solution-list" aria-label="Explorar soluciones">{solutions.map(s => <TabsTrigger className="solution-trigger" value={s.id} key={s.id}><s.icon aria-hidden="true" /><span><strong>{s.title}</strong><small>{s.teaser}</small></span><ArrowUpRight aria-hidden="true" /></TabsTrigger>)}</TabsList><div>{solutions.map(s => <TabsContent value={s.id} key={s.id}><SolutionPanel solution={s} /></TabsContent>)}</div></Tabs><Accordion type="single" defaultValue="desarrollo" collapsible className="mobile-solutions">{solutions.map(s => <AccordionItem className="mobile-solution-item" value={s.id} key={s.id}><AccordionTrigger className="mobile-solution-trigger"><span><s.icon aria-hidden="true" />{s.title}</span></AccordionTrigger><AccordionContent className="mobile-solution-content"><SolutionPanel solution={s} /></AccordionContent></AccordionItem>)}</Accordion></div></section>;
}

const phases = [
  { id: "descubrir", number: "01", title: "Descubrir", subtitle: "Entendemos tu operación", icon: Search, headline: "Primero, las preguntas correctas.", text: "Conversamos sobre tu forma de trabajar, dónde se repiten las tareas y qué necesita tu equipo. Así podemos delimitar el problema antes de proponer una herramienta.", activities: ["Revisar el proceso actual", "Identificar fricciones y prioridades", "Definir juntos un alcance inicial"], flow: ["Escuchar", "Entender", "Priorizar"] },
  { id: "disenar", number: "02", title: "Diseñar", subtitle: "Diseñamos la solución", icon: PencilRuler, headline: "Un camino claro, antes del código.", text: "Convertimos la necesidad en una propuesta concreta: cómo funcionará la solución, qué información necesita y qué debemos validar contigo.", activities: ["Definir flujos y funcionalidades", "Revisar una propuesta de solución", "Acordar prioridades y entregables"], flow: ["Proceso", "Propuesta", "Validación"] },
  { id: "construir", number: "03", title: "Construir", subtitle: "Construimos e integramos", icon: CodeXml, headline: "De una propuesta a una herramienta útil.", text: "Desarrollamos las funciones acordadas, conectamos los componentes necesarios y revisamos el comportamiento de la solución con escenarios de tu operación.", activities: ["Desarrollar las funciones acordadas", "Integrar los componentes del alcance", "Probar y ajustar la solución"], flow: ["Desarrollo", "Integración", "Pruebas"] },
  { id: "evolucionar", number: "04", title: "Evolucionar", subtitle: "Lanzamos y acompañamos", icon: Rocket, headline: "El lanzamiento es un nuevo comienzo.", text: "Ponemos la herramienta en uso y revisamos las necesidades que surgen. El soporte y el mantenimiento se acuerdan según tu solución.", activities: ["Coordinar la puesta en marcha", "Orientar el uso de la herramienta", "Acordar soporte y mejoras"], flow: ["Lanzamiento", "Soporte", "Mejora"] },
];
function Process() {
  return <section id="proceso" className="section process-section"><div className="wrap"><div className="process-heading reveal"><div><p className="eyebrow"><span className="chapter-number">02</span>CÓMO TRABAJAMOS</p><h2 className="section-heading">De una conversación<br />a una solución útil.</h2></div><p className="section-intro">Un recorrido claro, con decisiones compartidas. El alcance se acuerda para cada proyecto.</p></div><Tabs defaultValue="descubrir" orientation="vertical" className="process-tabs reveal"><TabsList className="process-list" aria-label="Etapas del proyecto">{phases.map(phase => <TabsTrigger value={phase.id} key={phase.id} className="process-trigger"><span className="step-number">{phase.number}</span><span className="step-copy"><strong>{phase.title}</strong><small>{phase.subtitle}</small></span><ArrowRight size={16} aria-hidden="true" /></TabsTrigger>)}</TabsList><div>{phases.map(phase => <TabsContent value={phase.id} key={phase.id} className="process-panel"><div className="panel-top"><span>FASE {phase.number} / {phase.title}</span><phase.icon aria-hidden="true" /></div><h3>{phase.headline}</h3><p>{phase.text}</p><ul>{phase.activities.map(activity => <li key={activity}><Check aria-hidden="true" />{activity}</li>)}</ul><div className="phase-visual" aria-hidden="true">{phase.flow.map((label, i) => <div className="contents" key={label}>{i > 0 && <i />}<span>{label}</span></div>)}</div></TabsContent>)}</div></Tabs></div></section>;
}

function Impact() {
  return <section id="proyectos" className="section"><div className="wrap"><div className="impact-heading reveal"><p className="eyebrow"><span className="chapter-number">03</span>SOFTWARE CON PROPÓSITO</p><h2 className="section-heading">Donde ayudamos<br />a crear impacto.</h2><p className="section-intro">Herramientas para tareas concretas. Desde organizar la gestión diaria hasta resolver un proceso propio de tu negocio.</p></div><div className="impact-grid reveal"><article className="impact-card"><div className="impact-copy"><p className="eyebrow">GESTIÓN EMPRESARIAL</p><h3>Información en orden.<br />Operaciones más claras.</h3><p>Cuando la gestión depende de registros dispersos, dar seguimiento se vuelve difícil. Exploremos sistemas financieros, de facturación, inventario o alquileres según tu necesidad.</p></div><div className="impact-visual"><div className="mock-top"><span>Espacio de gestión</span><small>Vista ilustrativa</small><Settings2 aria-hidden="true" /></div>{[{ icon: FileText, text: "Documento de venta", state: "Organizado" }, { icon: Layers3, text: "Registro de inventario", state: "Disponible" }, { icon: Database, text: "Información de gestión", state: "Centralizada" }].map(row => <div className="mock-row" key={row.text}><row.icon aria-hidden="true" /><span>{row.text}</span><span className="status-pill"><Check aria-hidden="true" />{row.state}</span></div>)}</div></article><article className="impact-card"><div className="impact-copy"><p className="eyebrow">SOFTWARE A LA MEDIDA</p><h3>Tu forma de trabajar.<br />Tu propia herramienta.</h3><p>Repetir tareas a mano consume atención. Diseñamos sistemas ajustados a tus procesos y automatizamos los pasos que pueden resolverse con software.</p></div><div className="impact-visual web-app-visual"><div className="web-window"><div className="device-head"><Monitor aria-hidden="true" />Mi operación</div><div className="mock-lines" aria-hidden="true"><i /><i /><i /><i /></div><div className="status-pill mt-4">Flujo de trabajo</div></div><span className="device-link" aria-hidden="true" /><div className="phone-window"><i /><div className="device-head"><Smartphone aria-hidden="true" />App</div><div className="mock-lines" aria-hidden="true"><i /><i /><i /></div></div></div></article></div><div className="product-index reveal"><div className="product-index-label">Sistemas publicados por MS Express</div><div className="product-index-items"><div><span>Dulus</span><small>Web y aplicación móvil</small></div><div><span>Sistema Financiero FAB</span><small>Gestión financiera</small></div><div><span>Facturación e Inventario FAB</span><small>Gestión comercial</small></div><div><span>Sistema de Alquileres FAB</span><small>Gestión de alquileres</small></div></div></div><p className="impact-footnote">Las interfaces son ilustrativas. No representan capturas de los productos ni resultados de clientes.</p></div></section>;
}
function Difference() {
  return <section className="section difference"><div className="wrap"><div className="reveal"><p className="eyebrow">MENOS FRICCIÓN. MÁS CLARIDAD.</p><h2 className="section-heading">No necesitas adaptar tu empresa a una herramienta genérica.</h2></div><div className="difference-grid reveal"><span className="difference-bridge" aria-hidden="true" /><div className="comparison-block"><div className="comparison-heading"><Unplug aria-hidden="true" />Herramientas desconectadas</div><h3>El trabajo entre las herramientas.</h3><ul><li><span aria-hidden="true">—</span>Copiar la misma información de un lugar a otro.</li><li><span aria-hidden="true">—</span>Buscar datos en archivos y conversaciones.</li><li><span aria-hidden="true">—</span>Depender de recordatorios y tareas repetitivas.</li></ul></div><div className="comparison-block"><div className="comparison-heading"><Network aria-hidden="true" />Una solución integrada</div><h3>Las herramientas trabajando contigo.</h3><ul><li><Check aria-hidden="true" />Procesos claros, con pasos definidos.</li><li><Check aria-hidden="true" />Información conectada donde se necesita.</li><li><Check aria-hidden="true" />Un equipo enfocado en decidir y resolver.</li></ul></div></div></div></section>;
}
function About() {
  const values = [{ icon: Eye, name: "Transparencia", text: "Claridad sobre lo que construimos y su alcance." }, { icon: HeartHandshake, name: "Servicio", text: "Escuchar y entender lo que necesitas resolver." }, { icon: Gem, name: "Calidad", text: "Herramientas útiles, pensadas para tu operación." }, { icon: ShieldCheck, name: "Compromiso", text: "Trabajar por el bienestar de clientes y equipo." }];
  return <section id="nosotros" className="section"><div className="wrap about-grid"><div className="reveal"><p className="eyebrow"><span className="chapter-number">04</span>SOBRE MS EXPRESS</p><h2 className="section-heading">Tecnología con criterio.<br /><span className="muted">Trato cercano.</span></h2><p className="section-intro">Somos Multi Servicios Express. Creamos software y ofrecemos servicios informáticos desde República Dominicana, con una idea clara: resolver necesidades reales con soluciones a la medida.</p><p className="section-intro">Nuestra visión combina calidad y precios justos. Nuestros valores guían cada conversación y cada solución.</p></div><div className="about-values reveal">{values.map(value => <div key={value.name}><value.icon aria-hidden="true" /><h3>{value.name}</h3><p>{value.text}</p></div>)}</div></div></section>;
}
const faqs = [
  { q: "¿Pueden desarrollar un sistema para mi empresa?", a: "Sí. MS Express desarrolla sistemas a la medida y automatiza procesos manuales. Primero revisamos tu necesidad para definir qué solución y alcance tienen sentido para tu operación." },
  { q: "¿Ofrecen soporte para sus aplicaciones?", a: "Sí. Al contratar las aplicaciones y soluciones de MS Express puedes contratar servicios de apoyo técnico. El soporte y las actualizaciones se definen según el sistema y el acuerdo correspondiente." },
  { q: "¿Cómo se brinda el soporte técnico?", a: "El soporte publicado por MS Express es remoto. Se coordina con el cliente el acceso necesario mediante la herramienta acordada para atender la solicitud." },
  { q: "¿Cómo puedo contactar al equipo?", a: "Puedes escribir a servicios@msexpressrd.com o a nuestro WhatsApp. También puedes llamar al (809) 221-3936. Cuéntanos qué parte de tu operación necesitas resolver." },
  { q: "¿Cómo funcionan las licencias de software?", a: "Los términos publicados contemplan una licencia mensual cuyo monto se comunica directamente a cada cliente. El alcance, el soporte y las condiciones de tu solución se revisan contigo; no hay una tarifa única publicada." },
];
function FAQ() {
  return <section id="preguntas" className="section faq-section"><div className="wrap faq-grid"><div className="reveal"><p className="eyebrow">ANTES DE CONVERSAR</p><h2 className="section-heading">Las preguntas<br />más comunes.</h2><p className="section-intro">Y si la tuya no está aquí,<br />podemos hablarla.</p><a href={CONTACT.whatsapp} target="_blank" rel="noopener noreferrer" className="text-link faq-link">Escríbenos por WhatsApp <ArrowUpRight aria-hidden="true" /></a></div><Accordion type="single" collapsible defaultValue="faq-0" className="faq-accordion reveal">{faqs.map((faq, i) => <AccordionItem value={"faq-" + i} key={faq.q}><AccordionTrigger className="faq-question">{faq.q}</AccordionTrigger><AccordionContent className="faq-answer">{faq.a}</AccordionContent></AccordionItem>)}</Accordion></div></section>;
}

function ContactForm() {
  const { register, handleSubmit, formState: { errors, isSubmitting }, setError, getValues, setValue, reset } = useForm<ContactValues>({ resolver: zodResolver(contactSchema), defaultValues: { name: "", company: "", email: "", phone: "", message: "", website: "" } });
  const [saved, setSaved] = useState(false);
  const [whatsappUrl, setWhatsappUrl] = useState(CONTACT.whatsapp);
  const successRef = useRef<HTMLDivElement>(null);
  const requestId = useRef<string | null>(null);
  useEffect(() => { const onInterest = (event: Event) => { if (!getValues("message")) setValue("message", "Me interesa " + String((event as CustomEvent).detail).toLowerCase() + ". Necesito resolver: "); }; window.addEventListener("solution-interest", onInterest); return () => window.removeEventListener("solution-interest", onInterest); }, [getValues, setValue]);
  useEffect(() => { if (saved) successRef.current?.focus(); }, [saved]);
  async function submit(values: ContactValues) {
    requestId.current ??= crypto.randomUUID();
    try {
      const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": requestId.current }, body: JSON.stringify(values) });
      const data: unknown = await response.json();
      const result = data && typeof data === "object" ? data as { ok?: unknown; error?: unknown } : {};
      if (!response.ok || result.ok !== true) throw new Error(typeof result.error === "string" ? result.error : "No pudimos guardar tu solicitud. Inténtalo de nuevo o escríbenos directamente.");
      const message = "Hola, MS Express. Soy " + values.name + (values.company ? ", de " + values.company : "") + ". " + values.message + "\nCorreo: " + values.email + (values.phone ? "\nTeléfono: " + values.phone : "");
      setWhatsappUrl(CONTACT.whatsapp + "?text=" + encodeURIComponent(message));
      setSaved(true);
    } catch (error) { setError("root", { message: error instanceof Error ? error.message : "No pudimos conectar. Tu información sigue en el formulario; puedes intentarlo de nuevo." }); }
  }
  if (saved) return <div className="success-state" role="status" ref={successRef} tabIndex={-1}><div className="success-icon"><CheckCheck size={28} aria-hidden="true" /></div><h3>Tu solicitud<br />quedó registrada.</h3><p>Gracias por contarnos lo que necesitas. Para iniciar el contacto directo con el equipo, continúa por WhatsApp con el mensaje que preparamos para ti.</p><a className="btn btn-primary" href={whatsappUrl} target="_blank" rel="noopener noreferrer">Continuar por WhatsApp <ArrowUpRight aria-hidden="true" /></a><small>La solicitud se guardó. No se envía un correo automático.</small><button onClick={() => { setSaved(false); requestId.current = null; reset(); }}>Registrar otra consulta</button></div>;
  return <form onSubmit={handleSubmit(submit)} noValidate className="contact-form" aria-label="Cuéntanos tu proyecto" aria-busy={isSubmitting}><div className="form-grid">{[{ key: "name", label: "Nombre", placeholder: "Tu nombre", type: "text", auto: "name", required: true }, { key: "company", label: "Empresa", placeholder: "Nombre de tu empresa", type: "text", auto: "organization", required: false }, { key: "email", label: "Correo", placeholder: "tu@empresa.com", type: "email", auto: "email", required: true }, { key: "phone", label: "Teléfono", placeholder: "+1 (809) 000-0000", type: "tel", auto: "tel", required: false }].map(field => { const key = field.key as keyof ContactValues; return <div className="field" key={key}><label htmlFor={"contact-" + key}>{field.label} {field.required ? <span aria-hidden="true">*</span> : <span>(opcional)</span>}</label><input id={"contact-" + key} type={field.type} autoComplete={field.auto} placeholder={field.placeholder} required={field.required} maxLength={key === "email" ? 254 : key === "phone" ? 40 : 150} aria-invalid={!!errors[key]} aria-describedby={errors[key] ? key + "-error" : undefined} {...register(key)} />{errors[key] && <span className="field-error" id={key + "-error"}>{errors[key]?.message}</span>}</div>; })}<div className="field full-field"><label htmlFor="contact-message">¿Qué necesitas resolver? <span aria-hidden="true">*</span></label><textarea id="contact-message" placeholder="Cuéntanos qué proceso te gustaría mejorar…" maxLength={3000} required aria-invalid={!!errors.message} aria-describedby={errors.message ? "message-error" : undefined} {...register("message")} />{errors.message && <span id="message-error" className="field-error">{errors.message.message}</span>}</div></div><div className="honeypot" aria-hidden="true"><label htmlFor="contact-website">Deja este campo vacío</label><input id="contact-website" tabIndex={-1} autoComplete="off" {...register("website")} /></div><p className="form-disclaimer">Usaremos tus datos para gestionar tu consulta. No incluyas información sensible. Consulta nuestra <a href={CONTACT.privacy} target="_blank" rel="noopener noreferrer">política de privacidad</a>.</p>{errors.root && <p className="form-error" role="alert">{errors.root.message}</p>}<button type="submit" disabled={isSubmitting} className="btn btn-primary submit-button">{isSubmitting ? <><LoaderCircle className="spinning" aria-hidden="true" />Guardando solicitud…</> : <>Iniciar conversación <ArrowRight aria-hidden="true" /></>}</button></form>;
}
function Contact() {
  return <section id="contacto" className="contact-section"><div className="wrap"><div className="contact-surface reveal"><div><p className="eyebrow">HABLEMOS DE TU OPERACIÓN</p><h2 className="section-heading">Tu próxima mejora operativa puede empezar hoy.</h2><p className="contact-description">Cuéntanos qué parte de tu negocio está creando más fricción. Evaluamos contigo la mejor forma de resolverla.</p><div className="contact-direct"><a href={"mailto:" + CONTACT.email}><Mail aria-hidden="true" />{CONTACT.email}</a><a href={"tel:" + CONTACT.tel}><Phone aria-hidden="true" />{CONTACT.phone}</a></div></div><ContactForm /></div></div></section>;
}
function Footer() {
  return <footer className="footer"><div className="wrap"><div className="footer-main"><div className="footer-brand"><Brand /><p className="footer-description">Software a la medida y soluciones digitales para que tu operación funcione mejor.</p></div><div className="footer-col"><h3>Explora</h3>{nav.map(item => <a href={"#" + item.id} key={item.id}>{item.label}</a>)}</div><div className="footer-col"><h3>Conversemos</h3><a href={"mailto:" + CONTACT.email}>{CONTACT.email}</a><a href={"tel:" + CONTACT.tel}>{CONTACT.phone}</a><a href={CONTACT.whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp ↗</a><p>República Dominicana</p></div></div><p className="footer-signature" aria-hidden="true">Software que mueve tu empresa.</p><div className="footer-base"><p>© {new Date().getFullYear()} Multi Servicios Express. Todos los derechos reservados.</p><div className="footer-legal"><a href={CONTACT.privacy} target="_blank" rel="noopener noreferrer">Privacidad ↗</a><a href={CONTACT.terms} target="_blank" rel="noopener noreferrer">Términos y condiciones ↗</a></div></div></div></footer>;
}
export default function Landing() {
  useEffect(() => {
    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)");
    if (reduced.matches || !("IntersectionObserver" in window)) return;
    const nodes = document.querySelectorAll<HTMLElement>(".reveal");
    nodes.forEach(node => { if (node.getBoundingClientRect().top < window.innerHeight) node.classList.add("is-visible"); });
    document.documentElement.classList.add("motion-ready");
    const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add("is-visible"); observer.unobserve(entry.target); } }), { threshold: .04 });
    nodes.forEach(node => observer.observe(node));
    return () => { observer.disconnect(); document.documentElement.classList.remove("motion-ready"); };
  }, []);
  return <><a className="skip-link" href="#contenido">Saltar al contenido</a><Navbar /><main id="contenido"><Hero /><Solutions /><Process /><Impact /><Difference /><About /><FAQ /><Contact /></main><Footer /></>;
}
